using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace YukiFramework.AddressableExtension.Editor
{
    public static class ResConditionerCodeGenerator
    {
        public const string DefaultOutputFilePath = ResourcesConditionerRuleSet.DefaultGeneratedFilePath;

        public sealed class GenerateResult
        {
            public bool Success;
            public string Message;
            public int RuleCount;
            public List<string> Warnings = new List<string>();
        }

        public static GenerateResult Generate(ResourcesConditionerRuleSet ruleSet)
        {
            var result = new GenerateResult();
            if (ruleSet == null)
            {
                result.Message = "规则集资产为空。";
                return result;
            }

            var enabledRules = ruleSet.Rules
                .Where(r => r != null && r.enabled)
                .ToList();

            result.Warnings.AddRange(ValidateRules(enabledRules));
            if (result.Warnings.Any(w => w.StartsWith("错误:")))
            {
                result.Message = "生成失败，请先修复规则错误。";
                return result;
            }

            var outputPath = ruleSet.GeneratedFilePath;
            var content = BuildCode(enabledRules, ruleSet.GeneratedNamespace);
            var outputDirectory = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outputDirectory) && !Directory.Exists(outputDirectory))
                Directory.CreateDirectory(outputDirectory);

            File.WriteAllText(outputPath, content, new UTF8Encoding(false));
            AssetDatabase.Refresh();

            result.Success = true;
            result.RuleCount = enabledRules.Count;
            result.Message = $"已生成 {outputPath}，规则数量：{enabledRules.Count}";
            return result;
        }

        public static List<string> ValidateRules(IReadOnlyList<ResourcesConditionerRuleData> rules)
        {
            var warnings = new List<string>();
            var classNames = new HashSet<string>(System.StringComparer.Ordinal);
            var keys = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);

            for (var i = 0; i < rules.Count; i++)
            {
                var rule = rules[i];
                if (rule == null)
                {
                    warnings.Add($"错误: 第 {i + 1} 条规则为空。");
                    continue;
                }

                if (!rule.enabled)
                    continue;

                if (string.IsNullOrWhiteSpace(rule.className))
                    warnings.Add($"错误: 第 {i + 1} 条规则类名为空。");
                else if (!IsValidTypeName(rule.className))
                    warnings.Add($"错误: 类名非法 ({rule.className})，需为合法 C# 标识符。");

                if (string.IsNullOrWhiteSpace(rule.rulePath))
                    warnings.Add($"警告: 第 {i + 1} 条规则 RulePath 为空 ({rule.className})。");

                if (string.IsNullOrWhiteSpace(rule.suffix))
                    warnings.Add($"错误: 第 {i + 1} 条规则后缀为空 ({rule.className})。");

                if (!classNames.Add(rule.className))
                    warnings.Add($"错误: 类名重复 ({rule.className})。");

                if (!keys.Add(rule.RuleKey))
                    warnings.Add($"警告: 规则路径+后缀重复 ({rule.RuleKey})。");
            }

            return warnings;
        }

        private static bool IsValidTypeName(string name)
        {
            return !string.IsNullOrEmpty(name) && Regex.IsMatch(name, @"^[a-zA-Z_][a-zA-Z0-9_]*$");
        }

        private static string BuildCode(List<ResourcesConditionerRuleData> rules, string namespaceName)
        {
            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// 此文件由 Resources Conditioner Editor 自动生成，请勿手动修改。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            foreach (var rule in rules.OrderBy(r => r.className, System.StringComparer.OrdinalIgnoreCase))
            {
                sb.AppendLine($"    public sealed class {rule.className} : IResourcesConditioner");
                sb.AppendLine("    {");
                sb.AppendLine($"        public string RulePath => \"{Escape(rule.rulePath)}\";");
                sb.AppendLine($"        public string Suffix => \"{Escape(rule.suffix)}\";");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string Escape(string value)
        {
            return value?.Replace("\\", "\\\\").Replace("\"", "\\\"") ?? string.Empty;
        }
    }
}
